source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CDBCheckboxView_Example', :exclusive => true do
  pod "CDBCheckboxView", :path => "../"
end

target 'CDBCheckboxView_Tests', :exclusive => true do
  pod "CDBCheckboxView", :path => "../"

  pod 'FBSnapshotTestCase'
end
